### ISSUE TITLE
CMS Test: CTA (Free)

### ISSUE THREAD

**Issue by julrich** [kickstartDS/storyblok-starter#2]
- Banner
  - [x] Button `target` should be Storyblok Content Type `Link` not `text`: https://github.com/kickstartDS/storyblok-starter/issues/1
- Highlighted
  - [x] Button `target` should be Storyblok Content Type `Link` not `text`: https://github.com/kickstartDS/storyblok-starter/issues/1
- Left Aligned
  - [x] Button `target` should be Storyblok Content Type `Link` not `text`: https://github.com/kickstartDS/storyblok-starter/issues/1

Storyblok Schema Types: https://www.storyblok.com/docs/schema-configuration
