### ISSUE TITLE
CMS Test: Features (Free)

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/storyblok-starter#3]
- Icon Centered
  - [x] Button target should be Storyblok Content Type Link not text: https://github.com/kickstartDS/storyblok-starter/issues/1
- Stack with Button
  - [x] Button target should be Storyblok Content Type Link not text: https://github.com/kickstartDS/storyblok-starter/issues/1
- List View
  - [x] Button target should be Storyblok Content Type Link not text: https://github.com/kickstartDS/storyblok-starter/issues/1
- Icon Beside with Link in Text
  - [x] Button target should be Storyblok Content Type Link not text: https://github.com/kickstartDS/storyblok-starter/issues/1
- Icon Intext With Link
  - [x] Button target should be Storyblok Content Type Link not text: https://github.com/kickstartDS/storyblok-starter/issues/1

Storyblok Schema Types: https://www.storyblok.com/docs/schema-configuration
